<?php
/**
 * Implements of hook_services_resources().
 */
function mywebservices_services_resources() {
  $api = array(
    'restaurants' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves posted restaurantss',
          'callback' => '_mywebservices_restaurants_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'fn',
              'type' => 'string',
              'description' => 'Function to perform',
              'source' => array('path' => '0'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'nitems',
              'type' => 'int',
              'description' => 'Number of latest items to get',
              'source' => array('param' => 'nitems'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'since',
              'type' => 'int',
              'description' => 'Posts from the last number of days',
              'source' => array('param' => 'since'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'type',
              'type' => 'string',
              'description' => 'restaurants of provided type',
              'source' => array('param' => 'type'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
  );
  return $api;
}

/**
 * Callback function for restaurants retrieve
 */
function _mywebservices_restaurants_retrieve($fn, $nitems, $timestamp, $type) {
  // Check for mad values

  $nitems = intval($nitems);
  $timestamp = intval($timestamp);
  return mywebservices_find_restaurants_items($nitems, $timestamp, $type);
}

/**
 * Gets restaurants posts
 */
function mywebservices_find_restaurants_items($nitems, $timestamp, $type) {

  // Compose query
  $query = db_select('node', 'n');
  $query->addField('ttd','name','restaurant_type');
  $query->join('node_revision', 'v', '(n.nid = v.nid) AND (n.vid = v.vid)');
  $query->join('users', 'u', 'n.uid = u.uid');
  //Type of veg or nonveg

    $query->join('taxonomy_index', 'ti', 'n.nid = ti.nid');  
    $query->join('taxonomy_term_data', 'ttd', 'ti.tid = ttd.tid'); 
  
  $query->join('field_data_body', 'b', '((b.entity_type = \'node\') AND (b.entity_id = n.nid) AND (b.revision_id = n.vid))');
  $query->fields('v', array('timestamp', 'title'));
  $query->addField('u', 'name', 'author');
  $query->addField('b', 'body_value', 'content');
  $query->condition('n.type', 'restaurants', '=');
  // How many days ago?
  if ($timestamp) {
   $query->condition('v.timestamp', time() - ($timestamp * 60 * 60 * 24), '>');
  }
  if($type){
    $query->condition('ttd.name', $type, '=');
  } 
  $query->orderBy('v.timestamp', 'DESC');
  // Limited by items?
  if ($nitems) {
    $query->range(0, $nitems);
  }
  $items = $query->execute()->fetchAll();

  return $items;
}
?>